name: Test DrupalPod
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Installs homebrew, mkcert, and ddev
        run: .gitpod/install-ddev.sh
      -
        name: Downloads ddev images
        run: .gitpod/download-ddev-images.sh
      -
        name: Configures Drupal root
        run: ddev composer run-script post-root-package-install
      -
        name: Configures SSH
        run: .gitpod/drupal/ssh/01-check-private-ssh.sh
      -
        name: Configures environment
        run: .gitpod/drupal/setup-dev-environment.sh
