name: Publish VSCode Extension
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
        working-directory: ./repos/drupalpod-ext
      -
        run: yarn install
        working-directory: ./repos/drupalpod-ext
      # @todo bump the version with each DrupalPod release automatically?
      #   This will mean the release doesn't have the new version in repos?
      # -
      #  run: yarn version --new-version ${{ github.event.release.tag_name }}
      #  working-directory: ./repos/drupalpod-ext
      #-
      #  run: git push origin
      -
        run: npm run ovsx publish -p ${{ secrets.OVSX_TOKEN }}
        working-directory: ./repos/drupalpod-ext
